src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100,unique=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="integer")
     */
    private $heartCount=0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getHeartCount(): ?int
    {
        return $this->heartCount;
    }

    public function setHeartCount(int $heartCount): self
    {
        $this->heartCount = $heartCount;

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }
    
    public function getImagePath(){
        return 'images/'.$this->getImageFilename();
    }

    public function incrementHeartCount(): self

    {
        $this->heartCount = $this->heartCount + 1;
        return $this;
    }

}

templates/estudiante/show.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ articles.title }} {%endblock%}
{% block body %}
{# cometarios! #}

{#<h1>Alumno: {{titulo}}</h1>
<div>
    <p>{{contenido}}</p>
</div>
<h2>Comentarios({{comentarios|length}})</h2>
<ul>
{% for comentario in comentarios %}
    <li>{{ comentario }}</li>
{% endfor %}
</ul>
<p>
<h2>Matricula({{matriculas|length}})</h2>
<ul>
{% for matricula in matriculas %}
    <li>{{ matricula }}</li>
{% endfor %}
</ul>
</p>
<p>
{{ 'text'|capitalize }}
</p>

<p>
  {%  if comentarios|length == 3   %}
       <p>Es mayor a 3</p>
  {% else %}
       <p>No es igual</p>
  {% endif %}
</p>#}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="show-article-container p-3 mt-4">
                <div class="row">
                    <div class="col-sm-12">
                        <img class="show-article-img" src="{{ asset( articles.imagePath) }}">
                        <div class="show-article-title-container d-inline-block pl-3 align-middle">
                            <span class="show-article-title "> {{ articles.title }}</span>
                            <br>
                            <span class="align-left article-details"><img class="article-author-img rounded-circle" src="{{ asset('images/alien-profile.png') }}"> {{ articles.author}} </span>
                            <span class="pl-2 article-details"> {{ articles.publishedAt ? articles.publishedAt|ago : 'unpublished' }}</span>
                            <span class="pl-2 article-details"> 
                                <span class="js-like-article-count">{{ articles.heartCount }}</span>
                                <a href="{{ path('article_toggle_heart',{variable:variable}) }}" class="fa fa-heart-o like-article js-like-article"></a></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="article-text">
                            {#{{ articleContent|raw }}#}
                            {#aqui {{ articles.content|markdown }}#}
                           {# {% for articulo in articles %} #}
                                
                                {{ articles.id }}<br>
                                {{ articles.title }}<br>
                                {{ articles.publishedAt ? articles.publishedAt|ago : 'unpublished' }}<br>
                                {{ articles.content|cached_markdown }}<br>
                                {# {% endfor %} #}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <p class="share-icons mb-5"><span class="pr-1">Share:</span> <i class="pr-1 fa fa-facebook-square"></i><i class="pr-1 fa fa-twitter-square"></i><i class="pr-1 fa fa-reddit-square"></i><i class="pr-1 fa fa-share-alt-square"></i></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <h3><i class="pr-3 fa fa-comment"></i>{{ comentarios|length }} Comentarios</h3>
                        <hr>

                        <div class="row mb-5">
                            <div class="col-sm-12">
                                <img class="comment-img rounded-circle" src="{{ asset('images/astronaut-profile.png') }}">
                                <div class="comment-container d-inline-block pl-3 align-top">
                                    <span class="commenter-name">Amy Oort</span>
                                    <div class="form-group">
                                        <textarea class="form-control comment-form" id="articleText" rows="1"></textarea>
                                    </div>
                                    <button type="submit" class="btn btn-info">Comment</button>
                                </div>
                            </div>
                        </div>
						{% for comentario in comentarios %}
                        <div class="row">
                            <div class="col-sm-12">
                                <img class="comment-img rounded-circle" src="{{ asset('images/alien-profile.png') }}">
                                <div class="comment-container d-inline-block pl-3 align-top">
                                    <span class="commenter-name">Mike Ferengi</span>
                                    <br>
                                    <span class="comment"> {{ comentario }}</span>
                                    <p><a href="#">Reply</a></p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
     <script src="{{ asset('js/show_article.js') }}"></script>
{% endblock %}